# Generated by Django 3.2.16 on 2022-11-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
    ]
